### ISSUE TITLE
Instant messaging and/or chat room

### ISSUE THREAD

**Issue by diogo-gomes** [minetest-mods/mob-engine#1]
### I propose to create a chat to talk about this mod.

I thought about [Gitter](https://gitter.iml) because it is connected to GitHub but for this, it is necessary that sofar or someone from minetest-mods team create a room directly for this mod because none of the administrators belongs to minetest-mods team.

**What is your opinion?**

**Comment by BrunoMine** [comment]
There are few collaborators yet. Perhaps the chat is useful in a more intense development flow.

**Comment by diogo-gomes** [comment]
But we need to talk about another things than issues.

We need to decide how to organize the development, etc

**Comment by BrunoMine** [comment]
I usually work based on issues or PR. But if you need to use other method, okay.

**Comment by diogo-gomes** [comment]
Okay. For now, we will use the forum to non related issues.
