### ISSUE TITLE
Eventually incorporate additions made in animals engine

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/mob-engine#16]
The [animals](https://github.com/danielmeek32/animals) mob engine also stems from CME, let's expand this one with the improvements made in the other.

**Comment by BrunoMine** [comment]
I would like to better understand the features, but there is no documentation that deals with this. Looking at the code, I believe we've already implemented everything.

**Comment by tacotexmex** [comment]
I can only remember a lot of dog collars.

**Comment by BrunoMine** [comment]
This project is full of bureaucratic rules, so even rushing things, it still takes time to bring new things.

**Comment by tacotexmex** [comment]
You can probably just close this.
