### ISSUE TITLE
License new code under LGPL 2.1

### ISSUE THREAD

**Issue by diogo-gomes** [minetest-mods/mob-engine#5]
Since the license LGPL 2.1 is a common license combination in the Minetest community as it is what Minetest and minetest_game use, I want to know your opinion about license new code under LGPL 2.1.

_**I think this change can bring more contributors and new great ideas to the project.**_

About the possibility of this change, on Mar 26, I create a question on [Open Source / Stack Exchange](https://opensource.stackexchange.com/questions/5295) where I ask:

> Can I relicense the new code under another license if I maintain the actual notice plus the new notice?

and the conclusion:

**Yes, we can license new code new code if we maintain the actual notice plus the new notice.**

> Yes, you can relicense this software. The LICENSE.txt file in the repository you link to is the notice referred to. You can modify this file to add your own copyright statement and your own license statement, as long as you preserve the current contents. Indeed, by doing so, you would be respecting all the conditions of the license.

### So, what you think about license new code under LGPL 2.1?

**Comment by BrunoMine** [comment]
What is the problem with a current licence?

**Comment by LNJ2** [comment]
I don't like the current license, it's not a "clean" official license, because it's modified by BlockMen. So I'd recommend using LGPLv2.1+ as alternative license, so that old code is licensed under modified zlib and, but officially compatible with LGPLv2.1+. If it's possible new code should be only licensed under LGPLv2.1+.

**Comment by BrunoMine** [comment]
If we are going to opt for an original license. Looks good.

**Comment by sofar** [comment]
The license may be compatible, but you may not remove the zlib license statement. Therefore, your only choices are:

a) do nothing (the zlib license is just fine)
b) dual license zlib+lgpl-2.1+

**Comment by diogo-gomes** [comment]
@BrunoMine @LNJ2
I think we have consensus, new code will be licensed under LGPL 2.1.

@sofar 
The @BlockMen's code will stay licensed with zlib along with current notice.
